# Generated by Django 5.2.9 on 2026-01-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_item_app_item_source_valid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionentry',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='collectionentry',
            name='unique_user_collection_item',
        ),
        migrations.RemoveIndex(
            model_name='collectionentry',
            name='app_collect_user_id_79b4ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionentry',
            name='app_collect_user_id_e7c8c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionentry',
            name='app_collect_user_id_5c40a5_idx',
        ),
    ]
