# Generated by Django 5.2.9 on 2026-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_item_app_item_source_valid_alter_item_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_uuid',
            field=models.CharField(help_text='Pocket Casts episode UUID', max_length=50, unique=True),
        ),
    ]
