# Generated by Django 5.2.9 on 2026-02-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_item_media_id_and_more'),
        ('app', '0081_item_series_name_item_series_position'),
    ]

    operations = [
    ]
