    # Generated by Django 5.2.9 on 2026-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_merge_20260216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('imdb', 'The Internet Movie Database'), ('tvdb', 'Skyhook (TVDB Mirror)'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('manual', 'Manual')], default='tmdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='studio',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('imdb', 'The Internet Movie Database'), ('tvdb', 'Skyhook (TVDB Mirror)'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('manual', 'Manual')], default='tmdb', max_length=20),
        ),
    ]
