# Generated by Django 5.2.9 on 2026-02-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_person_source_alter_podcastepisode_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
