# Generated by Django 5.2.9 on 2026-02-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_person_source_alter_podcastepisode_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_uuid',
            field=models.CharField(help_text='Pocket Casts episode UUID', max_length=255, unique=True),
        ),
    ]
