# Generated by Django 5.2.9 on 2026-02-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_remove_item_app_item_source_valid_alter_item_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_source', models.CharField(choices=[('tmdb', 'The Movie Database'), ('imdb', 'The IMDB Database'), ('tvdb', 'The TVDB Database'), ('trakt', 'Trakt'), ('tv_rage', 'TV Rage'), ('plex', 'Plex')], max_length=20)),
                ('metadata_source_identifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='app.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'metadata_source'), name='uniq_item_metadata_source'), models.CheckConstraint(condition=models.Q(('metadata_source__in', ['tmdb', 'imdb', 'tvdb', 'trakt', 'tv_rage', 'plex'])), name='externalid_valid_metadata_source')],
            },
        ),
    ]
