# Generated by Django 5.2.9 on 2026-02-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_item_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_uuid',
            field=models.CharField(help_text='Pocket Casts episode UUID', max_length=255, unique=True),
        ),
    ]
