services:
  yamtrack:
    container_name: yamtrack
    image: dmintz37/yamtrack:latest
    restart: unless-stopped
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - yamtrack-net

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - yamtrack-net

volumes:
  redis_data:


networks:
  yamtrack-net:
    driver: bridge
