# Generated by Django 5.2.9 on 2026-01-29 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_item_app_item_source_valid_and_more'),
        ('integrations', '0008_traktaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_source', models.CharField(max_length=20)),
                ('metadata_source_identifier', models.CharField(max_length=128)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast')], max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('found_metadata_source', models.CharField(blank=True, max_length=128, null=True)),
                ('found_metadata_source_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plex_id', models.IntegerField()),
                ('plex_history_id', models.IntegerField(unique=True)),
                ('viewed_at', models.DateTimeField()),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plex_history', to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plex_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item', 'viewed_at'), name='unique_user_item_viewed_at')],
            },
        ),
    ]
