# Generated by Django 5.2.9 on 2026-02-20 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_fix_movie_progress'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0008_traktaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_source', models.CharField(choices=[('tmdb', 'The Movie Database'), ('imdb', 'The IMDB Database'), ('tvdb', 'The TVDB Database'), ('trakt', 'Trakt'), ('tv_rage', 'TV Rage'), ('plex', 'Plex')], max_length=20)),
                ('metadata_source_identifier', models.CharField(max_length=128)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast')], max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('found_metadata_source', models.CharField(blank=True, max_length=128, null=True)),
                ('found_metadata_source_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
