# Generated by Django 5.2.9 on 2026-02-21 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_fix_movie_progress'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0009_unresolvedimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plex_id', models.IntegerField()),
                ('plex_history_id', models.IntegerField(db_index=True, unique=True)),
                ('viewed_at', models.DateTimeField(db_index=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('matched_media_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plex_history', to='app.item')),
                ('matched_media_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'app'), ('model__in', ['movie', 'episode'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plex_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['matched_media_id'], name='integration_matched_b35456_idx'), models.Index(fields=['item', 'viewed_at'], name='integration_item_id_08b6f6_idx'), models.Index(fields=['user', 'viewed_at'], name='integration_user_id_bf8f5a_idx'), models.Index(fields=['matched_media_type', 'matched_media_id'], name='integration_matched_5ac397_idx')],
            },
        ),
    ]
