# Generated by Django 5.2.9 on 2026-02-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_person_source_alter_podcastepisode_audio_url_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0010_plexhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plexhistory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plexhistory',
            name='matched_media_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='plexhistory',
            name='matched_media_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'app'), ('model__in', ['movie', 'episode'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='plexhistory',
            name='plex_history_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plexhistory',
            name='viewed_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='plexhistory',
            index=models.Index(fields=['matched_media_id'], name='integration_matched_b35456_idx'),
        ),
        migrations.AddIndex(
            model_name='plexhistory',
            index=models.Index(fields=['item', 'viewed_at'], name='integration_item_id_08b6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='plexhistory',
            index=models.Index(fields=['user', 'viewed_at'], name='integration_user_id_bf8f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='plexhistory',
            index=models.Index(fields=['matched_media_type', 'matched_media_id'], name='integration_matched_5ac397_idx'),
        ),
    ]
