# Generated by Django 5.2.9 on 2026-02-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_audiobookshelfaccount'),
        ('integrations', '0010_plexhistory'),
    ]

    operations = [
    ]
